name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Replace with your build command

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ secrets.FTP_SERVER }} # Set this secret in your GitHub repository
          username: ${{ secrets.FTP_USERNAME }} # Set this secret in your GitHub repository
          password: ${{ secrets.FTP_PASSWORD }} # Set this secret in your GitHub repository
          local-dir: ./build # Replace with the path to your build output directory
          remote-dir: /public_html # Replace with the remote directory on your cPanel server
